### ISSUE TITLE
[warn] Unknown user: 

### ISSUE THREAD

**Issue by sps31** [TychoTheTaco/Twitch-Drops-Bot#160] opened 2022-07-30 08:30 UTC
In the stream view mode without a drop, streamers not included in the category of the last running campaign are "Unknown user "
![image](https://user-images.githubusercontent.com/92994718/181898312-de1b2c1e-4bd4-4aed-b9bd-d737a146bf93.png)

**Comment by TychoTheTaco** [comment] 2022-07-31 22:56
This is a duplicate of #159

**Closed by TychoTheTaco** 2022-07-31 22:56 UTC
Labels: bug
