### ISSUE TITLE
Cant use auto login with 2FA + bad performance with raspberry pi

### ISSUE THREAD

**Issue by InstreakTV** [TychoTheTaco/Twitch-Drops-Bot#17] opened 2021-10-08 20:55 UTC
Hey, first of all thanks for the bot. I run it on my raspberry pi. But since the new update i cant put in the code for 2fa. I dont know what happened but its infinite loading. I had to remove it. Also the performance on my raspberry pi is really bad. Loading streams without the bot is no problem. But with the bot its often timing out.

**Comment by TychoTheTaco** [comment] 2021-10-09 21:08
The 2FA issue should be fixed in the latest update.

I'm not sure what is causing the performance issues because it seems to run fine on my end, although I don't have a raspberry pi to test with. Are you running the bot in a docker container? I have noticed it has some issues when using docker but I'm not sure of the cause. Are there any errors printed while you're using the bot?

**Comment by InstreakTV** [comment] 2021-10-11 19:42
Just starting it with remotedesktop. Maybe i have to start it with putty for better performance idk but i never used docker.

**Comment by mir0sv4L** [comment] 2021-11-20 15:43
How do you enter 2FA code? I'm running latest docker container but it gets stuck at this step
```[2021-11-20 15:30:10] [info] Loading config file: config.json
[2021-11-20 15:30:11] [info] Logging in...
[2021-11-20 15:30:13] [info] Checking for email verification...
[2021-11-20 15:30:43] [info] Email verification not found.
[2021-11-20 15:30:43] [info] Checking for 2FA verification...
[2021-11-20 15:30:43] [info] 2FA verification found.

**Comment by TychoTheTaco** [comment] 2021-11-21 04:29
Make sure to start the container with interactive mode `-i` so that you can enter the code. 

So you should start using one of these commands:
Windows: `docker run -v %cd%:/app/data -i --sig-proxy=false ghcr.io/tychothetaco/twitch-drops-bot`
Linux: `docker run -v ${PWD}:/app/data -i --sig-proxy=false ghcr.io/tychothetaco/twitch-drops-bot`

The output should look something like this:
```
[2021-11-21 04:26:28] [info] Loading config file: config.json
[2021-11-21 04:26:29] [info] Logging in...
[2021-11-21 04:26:31] [info] Checking for email verification...
[2021-11-21 04:27:01] [info] Email verification not found.
[2021-11-21 04:27:01] [info] Checking for 2FA verification...
[2021-11-21 04:27:01] [info] 2FA verification found.
prompt: code:  12345
[2021-11-21 04:27:21] [info] Logged in as username
[2021-11-21 04:27:21] [info] Saved cookies to ./cookies-username.json
[2021-11-21 04:27:21] [info] Updating drop campaigns...
[2021-11-21 04:27:21] [info] Found 123 campaigns.
```

**Comment by FelipeCalliari** [comment] 2021-11-21 21:14
> The 2FA issue should be fixed in the latest update.
> 
> I'm not sure what is causing the performance issues because it seems to run fine on my end, although I don't have a raspberry pi to test with. Are you running the bot in a docker container? I have noticed it has some issues when using docker but I'm not sure of the cause. Are there any errors printed while you're using the bot?

I have made some changes to work on my Raspberry Pi, things like increasing timeout, hiding videos (visibility: none), and others. May I send a pull request?

**Comment by TychoTheTaco** [comment] 2021-11-22 20:04
> I have made some changes to work on my Raspberry Pi, things like increasing timeout, hiding videos (visibility: none), and others. May I send a pull request?

Yes, you can send a pull request.

**Closed** 2022-01-04 01:49 UTC
